In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Stock Market Historical Data.csv")

In [3]:
df

      Company        Date Close/Last    Volume      Open       High       Low
0        AAPL  07/17/2023    $193.99  50520160   $191.90    $194.32   $191.81
1        AAPL  07/14/2023    $190.69  41616240   $190.23  $191.1799   $189.63
2        AAPL  07/13/2023    $190.54  41342340   $190.50    $191.19   $189.78
3        AAPL  07-12-2023    $189.77  60750250   $189.68    $191.70   $188.47
4        AAPL  07-11-2023    $188.08  46638120   $189.16    $189.30   $186.60
...       ...         ...        ...       ...       ...        ...       ...
25155    NFLX  07/24/2013   $34.4714  33395351  $35.6743   $36.0357  $34.3143
25156    NFLX  07/23/2013   $35.7514  76792963  $35.9143   $37.4621  $35.1714
25157    NFLX  07/22/2013   $37.4228  44791095  $38.1214   $38.3928  $36.7314
25158    NFLX  07/19/2013   $37.7966  18098750  $38.2043   $38.2784  $37.5971
25159    NFLX  07/18/2013   $38.0586  20418642  $38.6157   $38.6157  $37.7143

[25160 rows x 7 columns]

In [4]:
df.isna().sum()

Company       0
Date          0
Close/Last    0
Volume        0
Open          0
High          0
Low           0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     25160 non-null  object
 1   Date        25160 non-null  object
 2   Close/Last  25160 non-null  object
 3   Volume      25160 non-null  int64
 4   Open        25160 non-null  object
 5   High        25160 non-null  object
 6   Low         25160 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.3+ MB

In [8]:
df["Close/Last"] = (
    df["Close/Last"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [9]:
df["Close/Last"]

0        193.9900
1        190.6900
2        190.5400
3        189.7700
4        188.0800
           ...
25155     34.4714
25156     35.7514
25157     37.4228
25158     37.7966
25159     38.0586
Name: Close/Last, Length: 25160, dtype: float64

In [11]:
df["Open"] = (
    df["Open"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [13]:
df["High"] = (
    df["High"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [15]:
df["Low"] = (
    df["Low"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25160 entries, 0 to 25159
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     25160 non-null  object
 1   Date        25160 non-null  object
 2   Close/Last  25160 non-null  float64
 3   Volume      25160 non-null  int64
 4   Open        25160 non-null  float64
 5   High        25160 non-null  float64
 6   Low         25160 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.3+ MB

In [17]:
df["Date"] = pd.to_datetime(df["Date"],errors = 'coerce')

In [19]:
df["Date"].value_counts(dropna=False)

Date
NaT           9930
2023-07-17      10
2016-11-18      10
2016-10-25      10
2016-10-26      10
              ...
2020-03-20      10
2020-03-23      10
2020-03-24      10
2020-03-25      10
2013-07-18      10
Name: count, Length: 1524, dtype: int64

In [20]:
df.isna().sum()

Company          0
Date          9930
Close/Last       0
Volume           0
Open             0
High             0
Low              0
dtype: int64

In [21]:
df = df.dropna(subset=["Date"])

In [11]:
df

      Company       Date Close/Last    Volume      Open       High       Low
0        AAPL 2023-07-17    $193.99  50520160   $191.90    $194.32   $191.81
1        AAPL 2023-07-14    $190.69  41616240   $190.23  $191.1799   $189.63
2        AAPL 2023-07-13    $190.54  41342340   $190.50    $191.19   $189.78
10       AAPL 2023-06-30    $193.97  85213220   $191.63    $194.48   $191.26
11       AAPL 2023-06-29    $189.59  46347310   $189.08    $190.07   $188.94
...       ...        ...        ...       ...       ...        ...       ...
25155    NFLX 2013-07-24   $34.4714  33395351  $35.6743   $36.0357  $34.3143
25156    NFLX 2013-07-23   $35.7514  76792963  $35.9143   $37.4621  $35.1714
25157    NFLX 2013-07-22   $37.4228  44791095  $38.1214   $38.3928  $36.7314
25158    NFLX 2013-07-19   $37.7966  18098750  $38.2043   $38.2784  $37.5971
25159    NFLX 2013-07-18   $38.0586  20418642  $38.6157   $38.6157  $37.7143

[15230 rows x 7 columns]

In [22]:
df.isna().sum()

Company       0
Date          0
Close/Last    0
Volume        0
Open          0
High          0
Low           0
dtype: int64

In [23]:
x = df.drop(["Company","Date", "Close/Last"], axis=1)
y = df["Close/Last"]

In [24]:
x

         Volume      Open      High       Low
0      50520160  191.9000  194.3200  191.8100
1      41616240  190.2300  191.1799  189.6300
2      41342340  190.5000  191.1900  189.7800
10     85213220  191.6300  194.4800  191.2600
11     46347310  189.0800  190.0700  188.9400
...         ...       ...       ...       ...
25155  33395351   35.6743   36.0357   34.3143
25156  76792963   35.9143   37.4621   35.1714
25157  44791095   38.1214   38.3928   36.7314
25158  18098750   38.2043   38.2784   37.5971
25159  20418642   38.6157   38.6157   37.7143

[15230 rows x 4 columns]

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.preprocessing import StandardScaler
import numpy as np

In [27]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.20, random_state = 24
)

In [28]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [38]:
svm_r = SVR(
    kernel = "rbf"
)

In [39]:
svm_r.fit(x_train,y_train)

SVR()

In [41]:
y_pred = svm_r.predict(x_test)

In [42]:
y_pred

array([ 21.08684882,  26.68443062,  68.74866343, ...,  27.47643616,
       286.70512978,  88.73789068], shape=(3046,))

In [43]:
compariosn = pd.DataFrame({
    "Actual" : y_test,
    "Prediction" : y_pred
})

In [44]:
compariosn

         Actual  Prediction
21290   21.4300   21.086849
1888    24.3475   26.684431
12538   68.0900   68.748663
10894   66.5900   67.375604
20225   78.0900   78.568186
...         ...         ...
14276  127.5400  127.837579
7876    54.5000   54.143301
1826    28.0100   27.476436
23566  283.1100  286.705130
3411    88.2300   88.737891

[3046 rows x 2 columns]

In [46]:
compariosn['Error'] = compariosn['Actual'] - compariosn['Prediction']
compariosn

         Actual  Prediction     Error
21290   21.4300   21.086849  0.343151
1888    24.3475   26.684431 -2.336931
12538   68.0900   68.748663 -0.658663
10894   66.5900   67.375604 -0.785604
20225   78.0900   78.568186 -0.478186
...         ...         ...       ...
14276  127.5400  127.837579 -0.297579
7876    54.5000   54.143301  0.356699
1826    28.0100   27.476436  0.533564
23566  283.1100  286.705130 -3.595130
3411    88.2300   88.737891 -0.507891

[3046 rows x 3 columns]

In [47]:
mae = mean_absolute_error(y_test,y_pred)
print("MAE is :",mae)
mse = mean_squared_error(y_test,y_pred)
print("MSE is :",mse)
rmse = np.sqrt(mse)
print("RMSE is :",rmse)
r2 = r2_score(y_test,y_pred)
print("R2 Score is :",r2)

MAE is : 5.692338922754292
MSE is : 969.7648754082186
RMSE is : 31.141048078191243
R2 Score is : 0.9128336968557672